// <auto-generated />
using System;
using GymTecSQL_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymTecSQL_API.Migrations
{
    [DbContext(typeof(GymTecContext))]
    partial class GymTecContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymTecSQL_API.Models.ActividadLaboral", b =>
                {
                    b.Property<int>("IdActividadLaboral")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdActividadLaboral"));

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<int>("Horas")
                        .HasColumnType("int");

                    b.Property<int>("IdClase")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.HasKey("IdActividadLaboral");

                    b.ToTable("ActividadLaboral");
                });

            modelBuilder.Entity("GymTecSQL_API.Models.Clase", b =>
                {
                    b.Property<int>("IdClase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClase"));

                    b.Property<int>("CapacidadClase")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaClase")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("HoraFinalizacionClase")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicioClase")
                        .HasColumnType("time");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<int>("InstructorClase")
                        .HasColumnType("int");

                    b.Property<int>("ModalidadClase")
                        .HasColumnType("int");

                    b.Property<int>("TipoClase")
                        .HasColumnType("int");

                    b.HasKey("IdClase");

                    b.ToTable("Clase");
                });

            modelBuilder.Entity("GymTecSQL_API.Models.Cliente", b =>
                {
                    b.Property<int>("CedulaCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CedulaCliente"));

                    b.Property<string>("ApellidosCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<double>("IMCCliente")
                        .HasColumnType("float");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PesoCliente")
                        .HasColumnType("float");

                    b.HasKey("CedulaCliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("GymTecSQL_API.Models.Empleado", b =>
                {
                    b.Property<int>("CedulaEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CedulaEmpleado"));

                    b.Property<string>("CorreoEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdPlanilla")
                        .HasColumnType("int");

                    b.Property<int>("IdPuesto")
                        .HasColumnType("int");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<string>("NombreEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SalarioEmpleado")
                        .HasColumnType("float");

                    b.HasKey("CedulaEmpleado");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("GymTecSQL_API.Models.HorarioSucursal", b =>
                {
                    b.Property<int>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHorario"));

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("HoraApertura")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraCierre")
                        .HasColumnType("time");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int");

                    b.HasKey("IdHorario");

                    b.ToTable("HorarioSucursal");
                });

            modelBuilder.Entity("GymTecSQL_API.Models.Maquina", b =>
                {
                    b.Property<int>("IdMaquina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMaquina"));

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoEquipo")
                        .HasColumnType("int");

                    b.Property<string>("MarcaMaquina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMaquina");

                    b.ToTable("Maquina");
                });

            modelBuilder.Entity("GymTecSQL_API.Models.Planilla", b =>
                {
                    b.Property<int>("IdPlanilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlanilla"));

                    b.Property<string>("DescripcionPlanilla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPlanilla");

                    b.ToTable("Planilla");
                });

            modelBuilder.Entity("GymTecSQL_API.Models.Producto", b =>
                {
                    b.Property<int>("CodigoBarrasProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoBarrasProducto"));

                    b.Property<double>("CostoProducto")
                        .HasColumnType("float");

                    b.Property<string>("DescripcionProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodigoBarrasProducto");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("GymTecSQL_API.Models.Puesto", b =>
                {
                    b.Property<int>("IdPuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPuesto"));

                    b.Property<string>("DescripcionPuesto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPuesto");

                    b.ToTable("Puesto");
                });

            modelBuilder.Entity("GymTecSQL_API.Models.Servicio", b =>
                {
                    b.Property<int>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServicio"));

                    b.Property<string>("DescripcionServicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int");

                    b.HasKey("IdServicio");

                    b.ToTable("Servicio");
                });

            modelBuilder.Entity("GymTecSQL_API.Models.Spa", b =>
                {
                    b.Property<int>("IdSpa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSpa"));

                    b.Property<bool>("EstadoSpa")
                        .HasColumnType("bit");

                    b.HasKey("IdSpa");

                    b.ToTable("Spa");
                });

            modelBuilder.Entity("GymTecSQL_API.Models.SpaTratamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdSpa")
                        .HasColumnType("int");

                    b.Property<int>("IdTratamiento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SpaTratamiento");
                });

            modelBuilder.Entity("GymTecSQL_API.Models.Sucursal", b =>
                {
                    b.Property<int>("IdSucursal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSucursal"));

                    b.Property<string>("DireccionSucursal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime2");

                    b.Property<string>("HorarioAtencion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdSpa")
                        .HasColumnType("int");

                    b.Property<int>("IdTienda")
                        .HasColumnType("int");

                    b.HasKey("IdSucursal");

                    b.ToTable("Sucursal");
                });

            modelBuilder.Entity("GymTecSQL_API.Models.Tienda", b =>
                {
                    b.Property<int>("IdTienda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTienda"));

                    b.Property<bool>("EstadoTienda")
                        .HasColumnType("bit");

                    b.HasKey("IdTienda");

                    b.ToTable("Tienda");
                });

            modelBuilder.Entity("GymTecSQL_API.Models.TiendaProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoBarrasProducto")
                        .HasColumnType("int");

                    b.Property<int>("IdTienda")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TiendaProducto");
                });

            modelBuilder.Entity("GymTecSQL_API.Models.TipoEquipo", b =>
                {
                    b.Property<int>("IdTipoEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoEquipo"));

                    b.Property<string>("DescripcionTipoEquipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoEquipo");

                    b.ToTable("TipoEquipo");
                });

            modelBuilder.Entity("GymTecSQL_API.Models.Tratamiento", b =>
                {
                    b.Property<int>("IdTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTratamiento"));

                    b.Property<string>("NombreTratamiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTratamiento");

                    b.ToTable("Tratamiento");
                });
#pragma warning restore 612, 618
        }
    }
}
