---------------------------------------
-- Inicializar la base de datos
---------------------------------------
START TRANSACTION;
-- USE DATABASE "GymTecDB";

---------------------------------------
-- Creación de tablas
---------------------------------------

CREATE TABLE "AsistenciaClase" (
    "IdClase" integer NOT NULL,
    "CedulaCliente" integer NOT NULL,
    CONSTRAINT "PK_AsistenciaClase" PRIMARY KEY ("CedulaCliente", "IdClase")
);

CREATE TABLE "Cliente" (
    "CedulaCliente" integer NOT NULL,
    "NombreCliente" text NOT NULL,
    "ApellidosCliente" text NOT NULL,
    "FechaNacimiento" timestamp NOT NULL,
    "PesoCliente" double precision NOT NULL,
    "IMCCliente" double precision NOT NULL,
    "IdInstructor" integer,
    "DireccionCliente" text NOT NULL,
    "CorreoCliente" text NOT NULL,
    "PasswordCliente" text NOT NULL,
    CONSTRAINT "PK_Cliente" PRIMARY KEY ("CedulaCliente")
);

CREATE TABLE "Estado" (
    "IdEstado" integer GENERATED BY DEFAULT AS IDENTITY,
    "DescripcionEstado" text NOT NULL,
    CONSTRAINT "PK_Estado" PRIMARY KEY ("IdEstado")
);

CREATE TABLE "MarcaMaquina" (
    "IdMarcaMaquina" integer GENERATED BY DEFAULT AS IDENTITY,
    "NombreMarcaMaquina" text NOT NULL,
    CONSTRAINT "PK_MarcaMaquina" PRIMARY KEY ("IdMarcaMaquina")
);

CREATE TABLE "Planilla" (
    "IdPlanilla" integer GENERATED BY DEFAULT AS IDENTITY,
    "DescripcionPlanilla" text NOT NULL,
    CONSTRAINT "PK_Planilla" PRIMARY KEY ("IdPlanilla")
);

CREATE TABLE "Producto" (
    "CodigoBarrasProducto" integer NOT NULL,
    "NombreProducto" text NOT NULL,
    "DescripcionProducto" text NOT NULL,
    "CostoProducto" double precision NOT NULL,
    CONSTRAINT "PK_Producto" PRIMARY KEY ("CodigoBarrasProducto")
);

CREATE TABLE "Puesto" (
    "IdPuesto" integer GENERATED BY DEFAULT AS IDENTITY,
    "DescripcionPuesto" text UNIQUE NOT NULL,
    CONSTRAINT "PK_Puesto" PRIMARY KEY ("IdPuesto")
);

CREATE TABLE "Servicio" (
    "IdServicio" integer GENERATED BY DEFAULT AS IDENTITY,
    "DescripcionServicio" text NOT NULL,
    CONSTRAINT "PK_Servicio" PRIMARY KEY ("IdServicio")
);

CREATE TABLE "ServicioSucursal" (
    "IdServicio" integer NOT NULL,
    "IdSucursal" integer NOT NULL,
    CONSTRAINT "PK_ServicioSucursal" PRIMARY KEY ("IdServicio", "IdSucursal")
);

CREATE TABLE "SpaTratamiento" (
    "IdSpa" integer NOT NULL,
    "IdTratamiento" integer NOT NULL,
    CONSTRAINT "PK_SpaTratamiento" PRIMARY KEY ("IdSpa", "IdTratamiento")
);

CREATE TABLE "Sucursal" (
    "IdSucursal" integer GENERATED BY DEFAULT AS IDENTITY,
    "DireccionSucursal" text NOT NULL,
    "FechaApertura" timestamp NOT NULL,
    "HorarioAtencion" text NOT NULL,
    CONSTRAINT "PK_Sucursal" PRIMARY KEY ("IdSucursal")
);

CREATE TABLE "TiendaProducto" (
    "IdTienda" integer NOT NULL,
    "CodigoBarrasProducto" integer NOT NULL,
    CONSTRAINT "PK_TiendaProducto" PRIMARY KEY ("IdTienda", "CodigoBarrasProducto")
);

CREATE TABLE "TipoEquipo" (
    "IdTipoEquipo" integer GENERATED BY DEFAULT AS IDENTITY,
    "DescripcionTipoEquipo" text NOT NULL,
    CONSTRAINT "PK_TipoEquipo" PRIMARY KEY ("IdTipoEquipo")
);

CREATE TABLE "Tratamiento" (
    "IdTratamiento" integer GENERATED BY DEFAULT AS IDENTITY,
    "NombreTratamiento" text NOT NULL,
    CONSTRAINT "PK_Tratamiento" PRIMARY KEY ("IdTratamiento")
);

CREATE TABLE "Clase" (
    "IdClase" integer GENERATED BY DEFAULT AS IDENTITY,
    "TipoClase" integer NOT NULL,
    "IdInstructorClase" integer NOT NULL,
    "Grupal" boolean NOT NULL,
    "CapacidadClase" integer NOT NULL,
    "FechaClase" timestamp with time zone NOT NULL,
    "HoraInicioClase" time without time zone NOT NULL,
    "HoraFinalizacionClase" time without time zone NOT NULL,
    "IdSucursal" integer NOT NULL,
    CONSTRAINT "PK_Clase" PRIMARY KEY ("IdClase")
);

CREATE TABLE "Empleado" (
    "CedulaEmpleado" integer NOT NULL,
    "NombreEmpleado" text NOT NULL,
    "DireccionEmpleado" text NOT NULL,
    "IdSucursal" integer,
    "IdPuesto" integer NOT NULL,
    "IdPlanilla" integer NOT NULL,
    "SalarioEmpleado" double precision NOT NULL,
    "CorreoEmpleado" text NOT NULL,
    "PasswordEmpleado" text NOT NULL,
    CONSTRAINT "PK_Empleado" PRIMARY KEY ("CedulaEmpleado")
);

CREATE TABLE "Spa" (
    "IdSpa" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdSucursal" integer NOT NULL,
    "EstadoSpa" integer NOT NULL,
    CONSTRAINT "PK_Spa" PRIMARY KEY ("IdSpa")
);

CREATE TABLE "Tienda" (
    "IdTienda" integer GENERATED BY DEFAULT AS IDENTITY,
    "EstadoTienda" integer NOT NULL,
    "IdSucursal" integer NOT NULL,
    CONSTRAINT "PK_Tienda" PRIMARY KEY ("IdTienda")
);

CREATE TABLE "Maquina" (
    "IdMaquina" integer NOT NULL,
    "IdMarcaMaquina" integer NOT NULL,
    "IdSucursal" integer,
    "IdTipoEquipo" integer NOT NULL,
    CONSTRAINT "PK_Maquina" PRIMARY KEY ("IdMaquina")
);

CREATE TABLE "ActividadLaboral" (
    "IdActividadLaboral" integer GENERATED BY DEFAULT AS IDENTITY,
    "Año" integer NOT NULL,
    "Mes" integer NOT NULL,
    "Horas" integer NOT NULL,
    "IdEmpleado" integer NOT NULL,
    CONSTRAINT "PK_ActividadLaboral" PRIMARY KEY ("IdActividadLaboral")
);

CREATE TABLE "TelefonoSucursal" (
    "Telefono" integer NOT NULL,
    "IdSucursal" integer NOT NULL,
    CONSTRAINT "PK_TelefonoSucursal" PRIMARY KEY ("Telefono", "IdSucursal")
);

---------------------------------------
-- Constraints foreign keys
---------------------------------------

ALTER TABLE "Clase"
    ADD CONSTRAINT "FK_Clase_Sucursal_IdSucursal"
    FOREIGN KEY ("IdSucursal") REFERENCES "Sucursal" ("IdSucursal") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_Clase_Servivio_TipoClase"
    FOREIGN KEY ("TipoClase") REFERENCES "Servicio" ("IdServicio") ON DELETE RESTRICT;

ALTER TABLE "Empleado"
    ADD CONSTRAINT "FK_Empleado_Planilla_IdPlanilla"
    FOREIGN KEY ("IdPlanilla") REFERENCES "Planilla" ("IdPlanilla") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_Empleado_Puesto_IdPuesto"
    FOREIGN KEY ("IdPuesto") REFERENCES "Puesto" ("IdPuesto") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_Empleado_Sucursal_IdSucursal"
    FOREIGN KEY ("IdSucursal") REFERENCES "Sucursal" ("IdSucursal") ON DELETE RESTRICT;

ALTER TABLE "Spa"
    ADD CONSTRAINT "FK_Spa_Estado_EstadoSpa"
    FOREIGN KEY ("EstadoSpa") REFERENCES "Estado" ("IdEstado") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_Spa_Sucursal_IdSucursal"
    FOREIGN KEY ("IdSucursal") REFERENCES "Sucursal" ("IdSucursal") ON DELETE RESTRICT;

ALTER TABLE "Tienda"
    ADD CONSTRAINT "FK_Tienda_Estado_EstadoTienda"
    FOREIGN KEY ("EstadoTienda") REFERENCES "Estado" ("IdEstado") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_Tienda_Sucursal_IdSucursal"
    FOREIGN KEY ("IdSucursal") REFERENCES "Sucursal" ("IdSucursal") ON DELETE RESTRICT;

ALTER TABLE "Maquina"
    ADD CONSTRAINT "FK_Maquina_MarcaMaquina_IdMarcaMaquina"
    FOREIGN KEY ("IdMarcaMaquina") REFERENCES "MarcaMaquina" ("IdMarcaMaquina") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_Maquina_Sucursal_IdSucursal"
    FOREIGN KEY ("IdSucursal") REFERENCES "Sucursal" ("IdSucursal") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_Maquina_TipoEquipo_IdTipoEquipo"
    FOREIGN KEY ("IdTipoEquipo") REFERENCES "TipoEquipo" ("IdTipoEquipo") ON DELETE RESTRICT;

ALTER TABLE "ActividadLaboral"
    ADD CONSTRAINT "FK_ActividadLaboral_Empleado_IdEmpleado"
    FOREIGN KEY ("IdEmpleado") REFERENCES "Empleado" ("CedulaEmpleado") ON DELETE RESTRICT;

ALTER TABLE "Cliente"
    ADD CONSTRAINT "FK_Cliente_Empleado_IdInstructor"
    FOREIGN KEY ("IdInstructor") REFERENCES "Empleado" ("CedulaEmpleado") ON DELETE RESTRICT;

ALTER TABLE "TelefonoSucursal"
    ADD CONSTRAINT "FK_TelefonoSucursal_Sucursal"
    FOREIGN KEY ("IdSucursal") REFERENCES "Sucursal" ("IdSucursal") ON DELETE RESTRICT;

ALTER TABLE "TiendaProducto"
    ADD CONSTRAINT "FK_TiendaProducto_Tienda_IdTienda"
    FOREIGN KEY ("IdTienda") REFERENCES "Tienda" ("IdTienda") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_TiendaProducto_Producto_CodigoBarrasProducto"
    FOREIGN KEY ("CodigoBarrasProducto") REFERENCES "Producto" ("CodigoBarrasProducto") ON DELETE RESTRICT;

COMMIT;

---------------------------------------
-- Procedimientos Almacenados (Store Procedures)
---------------------------------------

-- 1) Generación de planilla
CREATE OR REPLACE FUNCTION sp_GenerarPlanilla()
RETURNS TABLE(
  IdSucursal integer,
  CedulaEmpleado integer,
  NombreEmpleado text,
  NumClases integer,
  HorasLaboradas integer,
  MontoPagar numeric
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    e."IdSucursal",
    e."CedulaEmpleado",
    e."NombreEmpleado",
    COALESCE(cl.count_clases,0) AS NumClases,
    COALESCE(al.horas,0) AS HorasLaboradas,
    CASE p."DescripcionPlanilla"
      WHEN 'Mensual' THEN e."SalarioEmpleado"
      WHEN 'Por Horas' THEN COALESCE(al.horas,0) * e."SalarioEmpleado"
      WHEN 'Por Clase (Grupal)' THEN COALESCE(cl.count_clases,0) * e."SalarioEmpleado"
      ELSE 0
    END AS MontoPagar
  FROM "Empleado" e
  JOIN "Planilla" p ON e."IdPlanilla"=p."IdPlanilla"
  LEFT JOIN (
    SELECT "IdInstructorClase", COUNT(*) AS count_clases
    FROM "Clase"
    GROUP BY "IdInstructorClase"
  ) cl ON cl."IdInstructorClase"=e."CedulaEmpleado"
  LEFT JOIN (
    SELECT "IdEmpleado", SUM("Horas") AS horas
    FROM "ActividadLaboral"
    GROUP BY "IdEmpleado"
  ) al ON al."IdEmpleado"=e."CedulaEmpleado";
END;
$$ LANGUAGE plpgsql;

-- 2) Copiar calendario de actividades (semana) a otra fecha
CREATE OR REPLACE FUNCTION sp_CopiarCalendarioActividadesSemana(
  fecha_origen date,
  fecha_destino date
) RETURNS void AS $$
BEGIN
  INSERT INTO "Clase"(
    "TipoClase","IdInstructorClase","Grupal","CapacidadClase",
    "FechaClase","HoraInicioClase","HoraFinalizacionClase","IdSucursal"
  )
  SELECT
    "TipoClase","IdInstructorClase","Grupal","CapacidadClase",
    (fecha_destino + (c."FechaClase"::date - fecha_origen))::timestamp,
    c."HoraInicioClase",c."HoraFinalizacionClase",c."IdSucursal"
  FROM "Clase" c
  WHERE c."FechaClase"::date >= fecha_origen
    AND c."FechaClase"::date < fecha_origen + interval '7 days';
END;
$$ LANGUAGE plpgsql;

-- 3) Copiar Gimnasio (tratamientos, productos y clases sin instructor)
CREATE OR REPLACE FUNCTION sp_CopiarGimnasio(
  id_sucursal_origen integer,
  id_sucursal_destino integer
) RETURNS void AS $$
DECLARE
  spa_origen integer;
  spa_destino integer;
  tienda_origen integer;
  tienda_destino integer;
BEGIN
  -- Obtener IdSpa y IdTienda asociados
  SELECT "IdSpa" INTO spa_origen FROM "Spa" WHERE "IdSucursal"=id_sucursal_origen;
  SELECT "IdSpa" INTO spa_destino FROM "Spa" WHERE "IdSucursal"=id_sucursal_destino;
  SELECT "IdTienda" INTO tienda_origen FROM "Tienda" WHERE "IdSucursal"=id_sucursal_origen;
  SELECT "IdTienda" INTO tienda_destino FROM "Tienda" WHERE "IdSucursal"=id_sucursal_destino;

  -- Copiar tratamientos al nuevo Spa
  INSERT INTO "SpaTratamiento"("IdSpa","IdTratamiento")
    SELECT spa_destino, st."IdTratamiento"
    FROM "SpaTratamiento" st
    WHERE st."IdSpa"=spa_origen;

  -- Copiar productos a la nueva Tienda
  INSERT INTO "TiendaProducto"("IdTienda","CodigoBarrasProducto")
    SELECT tienda_destino, tp."CodigoBarrasProducto"
    FROM "TiendaProducto" tp
    WHERE tp."IdTienda"=tienda_origen;

  -- Copiar clases sin asignar instructor
  INSERT INTO "Clase"(
    "TipoClase","IdInstructorClase","Grupal","CapacidadClase",
    "FechaClase","HoraInicioClase","HoraFinalizacionClase","IdSucursal"
  )
    SELECT c."TipoClase", NULL, c."Grupal", c."CapacidadClase",
      c."FechaClase", c."HoraInicioClase", c."HoraFinalizacionClase", id_sucursal_destino
    FROM "Clase" c
    WHERE c."IdSucursal"=id_sucursal_origen;
END;
$$ LANGUAGE plpgsql;

-- 4) Registrar asistencia en clase (valida cupo)
CREATE OR REPLACE FUNCTION sp_RegistrarAsistenciaClase(
  cedula_cliente integer,
  id_clase integer
) RETURNS void AS $$
DECLARE
  capacidad integer;
  inscritos integer;
BEGIN
  SELECT "CapacidadClase" INTO capacidad FROM "Clase" WHERE "IdClase"=id_clase;
  SELECT COUNT(*) INTO inscritos FROM "AsistenciaClase" WHERE "IdClase"=id_clase;
  IF inscritos >= capacidad THEN
    RAISE EXCEPTION 'La clase % está llena', id_clase;
  END IF;
  INSERT INTO "AsistenciaClase"("CedulaCliente","IdClase") VALUES(cedula_cliente,id_clase);
END;
$$ LANGUAGE plpgsql;

---------------------------------------
-- Triggers y funciones auxiliares
---------------------------------------

-- 1) Evitar modificación de tratamientos default
CREATE OR REPLACE FUNCTION trg_no_modificar_tratamiento_default() RETURNS trigger AS $$
BEGIN
  IF OLD."NombreTratamiento" IN ('Masaje Relajante','Masaje Descarga Muscular','Sauna','Baños a Vapor') THEN
    RAISE EXCEPTION 'No se puede modificar el tratamiento default %', OLD."NombreTratamiento";
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER no_update_default_tratamientos
BEFORE UPDATE ON "Tratamiento"
FOR EACH ROW EXECUTE FUNCTION trg_no_modificar_tratamiento_default();

-- 2) Evitar eliminación de tratamientos default o asociados
CREATE OR REPLACE FUNCTION trg_no_eliminar_tratamiento() RETURNS trigger AS $$
BEGIN
  IF OLD."NombreTratamiento" IN ('Masaje Relajante','Masaje Descarga Muscular','Sauna','Baños a Vapor')
    OR EXISTS(SELECT 1 FROM "SpaTratamiento" WHERE "IdTratamiento"=OLD."IdTratamiento") THEN
    RAISE EXCEPTION 'No se puede eliminar el tratamiento %', OLD."NombreTratamiento";
  END IF;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER no_delete_tratamientos
BEFORE DELETE ON "Tratamiento"
FOR EACH ROW EXECUTE FUNCTION trg_no_eliminar_tratamiento();

-- 3) Evitar eliminación de puestos default
CREATE OR REPLACE FUNCTION trg_no_eliminar_puesto_default() RETURNS trigger AS $$
BEGIN
  IF OLD."DescripcionPuesto" IN ('Administrador','Instructor','Dependiente Spa','Dependiente Tienda') THEN
    RAISE EXCEPTION 'No se puede eliminar el puesto default %', OLD."DescripcionPuesto";
  END IF;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER no_delete_puestos_default
BEFORE DELETE ON "Puesto"
FOR EACH ROW EXECUTE FUNCTION trg_no_eliminar_puesto_default();

---------------------------------------
-- Vistas
---------------------------------------

-- 1) Clases con cupos disponibles
CREATE OR REPLACE VIEW vw_ClasesDisponibles AS
SELECT
  c."IdClase",
  c."TipoClase",
  c."FechaClase",
  c."HoraInicioClase",
  c."HoraFinalizacionClase",
  c."CapacidadClase" - COUNT(a."CedulaCliente") AS cupos_disponibles
FROM "Clase" c
LEFT JOIN "AsistenciaClase" a ON c."IdClase"=a."IdClase"
GROUP BY c."IdClase",c."TipoClase",c."FechaClase",c."HoraInicioClase",c."HoraFinalizacionClase",c."CapacidadClase";

-- 2) Empleados y su tipo de planilla por sucursal
CREATE OR REPLACE VIEW vw_EmpleadosPorSucursal AS
SELECT
  e."CedulaEmpleado",
  e."NombreEmpleado",
  e."IdSucursal",
  p."DescripcionPlanilla"
FROM "Empleado" e
JOIN "Planilla" p ON e."IdPlanilla"=p."IdPlanilla";