---------------------------------------
-- Inicializar la base de datos
-------------------
START TRANSACTION;
USE DATABASE "GymTecDB";

---------------------------------------
-- Creacion de las tablas
-------------------
CREATE TABLE "AsistenciaClase" (
    "IdClase" integer NOT NULL,
    "CedulaCliente" integer NOT NULL,
    CONSTRAINT "PK_AsistenciaClase" PRIMARY KEY ("CedulaCliente", "IdClase")
);

CREATE TABLE "Cliente" (
    "CedulaCliente" integer NOT NULL,
    "NombreCliente" text NOT NULL,
    "ApellidosCliente" text NOT NULL,
    "FechaNacimiento" timestamp with time zone NOT NULL,
    "PesoCliente" double precision NOT NULL,
    "IMCCliente" double precision NOT NULL,
    "DireccionCliente" text NOT NULL,
    "CorreoCliente" text NOT NULL,
    "PasswordCliente" text NOT NULL,
    CONSTRAINT "PK_Cliente" PRIMARY KEY ("CedulaCliente")
);

CREATE TABLE "Estado" (
    "IdEstado" integer GENERATED BY DEFAULT AS IDENTITY,
    "DescripcionEstado" text NOT NULL,
    CONSTRAINT "PK_Estado" PRIMARY KEY ("IdEstado")
);

CREATE TABLE "MarcaMaquina" (
    "IdMarcaMaquina" integer GENERATED BY DEFAULT AS IDENTITY,
    "NombreMarcaMaquina" text NOT NULL,
    CONSTRAINT "PK_MarcaMaquina" PRIMARY KEY ("IdMarcaMaquina")
);

CREATE TABLE "Planilla" (
    "IdPlanilla" integer GENERATED BY DEFAULT AS IDENTITY,
    "DescripcionPlanilla" text NOT NULL,
    CONSTRAINT "PK_Planilla" PRIMARY KEY ("IdPlanilla")
);

CREATE TABLE "Producto" (
    "CodigoBarrasProducto" integer NOT NULL,
    "NombreProducto" text NOT NULL,
    "DescripcionProducto" text NOT NULL,
    "CostoProducto" double precision NOT NULL,
    CONSTRAINT "PK_Producto" PRIMARY KEY ("CodigoBarrasProducto")
);

CREATE TABLE "Puesto" (
    "IdPuesto" integer GENERATED BY DEFAULT AS IDENTITY,
    "DescripcionPuesto" text NOT NULL,
    CONSTRAINT "PK_Puesto" PRIMARY KEY ("IdPuesto")
);

CREATE TABLE "Servicio" (
    "IdServicio" integer GENERATED BY DEFAULT AS IDENTITY,
    "DescripcionServicio" text NOT NULL,
    CONSTRAINT "PK_Servicio" PRIMARY KEY ("IdServicio")
);

CREATE TABLE "ServicioSucursal" (
    "IdServicio" integer NOT NULL,
    "IdSucursal" integer NOT NULL,
    CONSTRAINT "PK_ServicioSucursal" PRIMARY KEY ("IdServicio", "IdSucursal")
);

CREATE TABLE "SpaTratamiento" (
    "IdSpa" integer NOT NULL,
    "IdTratamiento" integer NOT NULL,
    CONSTRAINT "PK_SpaTratamiento" PRIMARY KEY ("IdSpa", "IdTratamiento")
);

CREATE TABLE "Sucursal" (
    "IdSucursal" integer GENERATED BY DEFAULT AS IDENTITY,
    "DireccionSucursal" text NOT NULL,
    "FechaApertura" timestamp with time zone NOT NULL,
    "HorarioAtencion" text NOT NULL,
    CONSTRAINT "PK_Sucursal" PRIMARY KEY ("IdSucursal")
);

CREATE TABLE "TiendaProducto" (
    "IdTienda" integer NOT NULL,
    "CodigoBarrasProducto" integer NOT NULL,
    CONSTRAINT "PK_TiendaProducto" PRIMARY KEY ("IdTienda", "CodigoBarrasProducto")
);

CREATE TABLE "TipoEquipo" (
    "IdTipoEquipo" integer GENERATED BY DEFAULT AS IDENTITY,
    "DescripcionTipoEquipo" text NOT NULL,
    CONSTRAINT "PK_TipoEquipo" PRIMARY KEY ("IdTipoEquipo")
);

CREATE TABLE "Tratamiento" (
    "IdTratamiento" integer GENERATED BY DEFAULT AS IDENTITY,
    "NombreTratamiento" text NOT NULL,
    CONSTRAINT "PK_Tratamiento" PRIMARY KEY ("IdTratamiento")
);

CREATE TABLE "Clase" (
    "IdClase" integer GENERATED BY DEFAULT AS IDENTITY,
    "TipoClase" integer NOT NULL,
    "IdInstructorClase" integer NOT NULL,
    "Grupal" boolean NOT NULL,
    "CapacidadClase" integer NOT NULL,
    "FechaClase" timestamp with time zone NOT NULL,
    "HoraInicioClase" time without time zone NOT NULL,
    "HoraFinalizacionClase" time without time zone NOT NULL,
    "IdSucursal" integer NOT NULL,
    CONSTRAINT "PK_Clase" PRIMARY KEY ("IdClase"),
    CONSTRAINT "FK_Clase_Sucursal_IdSucursal" FOREIGN KEY ("IdSucursal") REFERENCES "Sucursal" ("IdSucursal") ON DELETE RESTRICT,
    CONSTRAINT "FK_Clase_Servivio_TipoClase" FOREIGN KEY ("TipoClase") REFERENCES "Servicio" ("IdServicio") ON DELETE CASCADE
);

CREATE TABLE "Empleado" (
    "CedulaEmpleado" integer NOT NULL,
    "NombreEmpleado" text NOT NULL,
    "DireccionEmpleado" text NOT NULL,
    "IdSucursal" integer NOT NULL,
    "IdPuesto" integer NOT NULL,
    "IdPlanilla" integer NOT NULL,
    "SalarioEmpleado" double precision NOT NULL,
    "CorreoEmpleado" text NOT NULL,
    "PasswordEmpleado" text NOT NULL,
    CONSTRAINT "PK_Empleado" PRIMARY KEY ("CedulaEmpleado"),
    CONSTRAINT "FK_Empleado_Planilla_IdPlanilla" FOREIGN KEY ("IdPlanilla") REFERENCES "Planilla" ("IdPlanilla") ON DELETE RESTRICT,
    CONSTRAINT "FK_Empleado_Puesto_IdPuesto" FOREIGN KEY ("IdPuesto") REFERENCES "Puesto" ("IdPuesto") ON DELETE RESTRICT,
    CONSTRAINT "FK_Empleado_Sucursal_IdSucursal" FOREIGN KEY ("IdSucursal") REFERENCES "Sucursal" ("IdSucursal") ON DELETE RESTRICT
);

CREATE TABLE "Spa" (
    "IdSpa" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdSucursal" integer NOT NULL,
    "EstadoSpa" integer NOT NULL,
    CONSTRAINT "PK_Spa" PRIMARY KEY ("IdSpa"),
    CONSTRAINT "FK_Spa_Estado_EstadoSpa" FOREIGN KEY ("EstadoSpa") REFERENCES "Estado" ("IdEstado") ON DELETE RESTRICT,
    CONSTRAINT "FK_Spa_Sucursal_IdSucursal" FOREIGN KEY ("IdSucursal") REFERENCES "Sucursal" ("IdSucursal") ON DELETE RESTRICT
);

CREATE TABLE "Tienda" (
    "IdTienda" integer GENERATED BY DEFAULT AS IDENTITY,
    "EstadoTienda" integer NOT NULL,
    "IdSucursal" integer NOT NULL,
    CONSTRAINT "PK_Tienda" PRIMARY KEY ("IdTienda"),
    CONSTRAINT "FK_Tienda_Estado_EstadoTienda" FOREIGN KEY ("EstadoTienda") REFERENCES "Estado" ("IdEstado") ON DELETE RESTRICT,
    CONSTRAINT "FK_Tienda_Sucursal_IdSucursal" FOREIGN KEY ("IdSucursal") REFERENCES "Sucursal" ("IdSucursal") ON DELETE RESTRICT
);

CREATE TABLE "Maquina" (
    "IdMaquina" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdMarcaMaquina" integer NOT NULL,
    "IdSucursal" integer NOT NULL,
    "IdTipoEquipo" integer NOT NULL,
    CONSTRAINT "PK_Maquina" PRIMARY KEY ("IdMaquina"),
    CONSTRAINT "FK_Maquina_MarcaMaquina_IdMarcaMaquina" FOREIGN KEY ("IdMarcaMaquina") REFERENCES "MarcaMaquina" ("IdMarcaMaquina") ON DELETE RESTRICT,
    CONSTRAINT "FK_Maquina_Sucursal_IdSucursal" FOREIGN KEY ("IdSucursal") REFERENCES "Sucursal" ("IdSucursal") ON DELETE CASCADE,
    CONSTRAINT "FK_Maquina_TipoEquipo_IdTipoEquipo" FOREIGN KEY ("IdTipoEquipo") REFERENCES "TipoEquipo" ("IdTipoEquipo") ON DELETE RESTRICT
);

CREATE TABLE "ActividadLaboral" (
    "IdActividadLaboral" integer GENERATED BY DEFAULT AS IDENTITY,
    "Año" integer NOT NULL,
    "Mes" integer NOT NULL,
    "Horas" integer NOT NULL,
    "IdEmpleado" integer NOT NULL,
    CONSTRAINT "PK_ActividadLaboral" PRIMARY KEY ("IdActividadLaboral"),
    CONSTRAINT "FK_ActividadLaboral_Empleado_IdEmpleado" FOREIGN KEY ("IdEmpleado") REFERENCES "Empleado" ("CedulaEmpleado") ON DELETE CASCADE
);
---------------------------------------
-- Indices externos
-------------------

CREATE INDEX "IX_ActividadLaboral_IdEmpleado" ON "ActividadLaboral" ("IdEmpleado");

CREATE INDEX "IX_Clase_IdSucursal" ON "Clase" ("IdSucursal");

CREATE INDEX "IX_Empleado_IdPlanilla" ON "Empleado" ("IdPlanilla");

CREATE INDEX "IX_Empleado_IdPuesto" ON "Empleado" ("IdPuesto");

CREATE INDEX "IX_Empleado_IdSucursal" ON "Empleado" ("IdSucursal");

CREATE INDEX "IX_Maquina_IdMarcaMaquina" ON "Maquina" ("IdMarcaMaquina");

CREATE INDEX "IX_Maquina_IdSucursal" ON "Maquina" ("IdSucursal");

CREATE INDEX "IX_Maquina_IdTipoEquipo" ON "Maquina" ("IdTipoEquipo");

CREATE INDEX "IX_Spa_EstadoSpa" ON "Spa" ("EstadoSpa");

CREATE INDEX "IX_Spa_IdSucursal" ON "Spa" ("IdSucursal");

CREATE INDEX "IX_Tienda_EstadoTienda" ON "Tienda" ("EstadoTienda");

CREATE INDEX "IX_Tienda_IdSucursal" ON "Tienda" ("IdSucursal");

COMMIT;

